# Generated by Django 3.2.6 on 2021-08-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210819_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
